name: Maze Creator CICD
run-name: deploy maze-creator app to cloudflare workers
on:
  workflow_dispatch:
  push:
    branches:
      - feature/*

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: install cargo
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - run: cd frontend && npm ci
      - run: cd wasm && rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-pack
  lint:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run linter
        run: cd frontend && npm run lint
      - name: Run rustfmt
        run: cd frontend/wasm && cargo fmt -- --check
  test:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
          key: rust-${{ hashfiles('**/Cargo.lock') }}
          restore-keys: |
            rust-
      - name: Run tests
        run: cd frontend/wasm && cargo test
  build:
    needs: [test, lint]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
          key: rust-${{ hashfiles('frontend/wasm/Cargo.lock') }}
          restore-keys: |
            rust-
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: npm-${{ hashfiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - run: cd frontend/wasm && LOG_LEVEL=Info wasm-pack build --target bundler --out-dir ../src/wasm
      - name: build
        uses: actions/setup-node@v4
      - run: npm install && npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: npm install wrangler -g
      - run: cd frontend
      - name: Deploy to Cloudflare Workers
        run: npm run preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
