name: Maze Creator CICD
run-name: deploy maze-creator app to cloudflare workers
on:
  workflow_dispatch:
  branches:
    - feature/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-pack
      - name: Run linter
        run: cd frontend && npm run linter
      - name: Run rustfmt
        run: cd wasm && cargo fmt -- --check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
      - name: Run tests
        run: cd frontend/wasm32 && cargo test
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
      - run: LOG_LEVEL=Info wasm-pack build --target bundler --out-dir ../src/wasm
      - name: build
        uses: actions/setup-node@v4
      - run: npm install && npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to Cloudflare Workers
        run: npm run preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
